sut:
  build: .
  links:
    - mongodb
    - elasticsearch
  command: npm test
mongodb:
  image: tutum/mongodb:3.0
  environment:
    - OPLOG_SIZE=1
  ports:
    - "27018:27017"
    - "28018:28017"
elasticsearch:
    image: tutum/elasticsearch:latest
    ports:
      - "9200:9200"
      - "9300:9300"
